services:
  db:
    image: mysql:8
    container_name: telegram_bot_popovk
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: telegram_bot_db_popovk
      MYSQL_USER: bot_user
      MYSQL_PASSWORD: bot_password
    ports:
      - "3318:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql:ro

  bot:
    build: .
    container_name: telegram-bot
    restart: always
    depends_on:
      - db
    environment:
      BOT_TOKEN: "8369855279:AAG-aT2oxut4lOK8maWkCV0IQM1Wh6G761A"
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: bot_user
      DB_PASSWORD: bot_password
      DB_NAME: telegram_bot_db_popovk

volumes:
  db_data:


